apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id}}-service
  description: 'The Liberty service for ${{values.component_id}} (${{values.description}})'
  annotations:
    argocd/app-name: ${{values.component_id}}-dev
    backstage.io/kubernetes-id: ${{values.component_id}}
    backstage.io/kubernetes-namespace: ${{values.namespace}}
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ${{values.repoOwner}}/${{values.repoName}}
    janus-idp.io/tekton : ${{values.component_id}}
    argocd/app-selector: ${{values.component_id}}-dev
    openliberty.io/app-kind: OpenLibertyApplication
  labels:
    backstage.io/kubernetes-id: ${{values.component_id}}
  tags:
    - java
    - liberty
    - maven
    - example
  links:
    - url: https://console-openshift-console${{values.cluster_id}}/k8s/ns/${{values.namespace}}/deployments/${{values.component_id}}
      title: Deployment
      icon: web
    - url: https://openliberty.io/docs/latest/overview.html
      title: Open Liberty Docs
      icon: web
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner | dump}}
  providesApis:
    - ${{values.component_id}}-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.component_id}}-api
  description: API surface exposed by the Liberty service
  links:
    - url: https://${{values.component_id}}-${{values.namespace}}${{values.cluster_id}}/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://${{values.git_host}}/${{values.repoOwner}}/${{values.repoName}}/-/blob/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: ${{values.owner | dump}}
  definition:
    $text: ./src/main/resources/META-INF/openapi.yaml
